version: "3"

services:
  app:
    build: .
    command: bash -c "yarn install && npx prisma migrate dev --name init && yarn start"
    container_name: app
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    depends_on:
      - database

  db:
    container_name: dmchk-pm-db
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=dmchk-pm
      - MYSQL_ROOT_PASSWORD=dmchk@123
      - TZ=America/Sao_Paulo
    ports:
      - "3306:3306"
